- name: Actualizar Apache y PHP en instancia de Azure
  hosts: azure
  become: true

  tasks:
    - name: Actualizar paquetes de sistema
      apt:
        update_cache: yes

    - name: Actualizar Apache
      apt:
        name: apache2
        state: latest

    - name: Actualizar PHP
      apt:
        name: php
        state: latest
